### ISSUE TITLE
Replace Registry contract

### ISSUE THREAD

**Issue by royscheeren** [ASCS-eV/envited-x-data-space#288]
# Scope

Theres a new registry contract that we have to communicate with

# Definition of done

The contract address is updated

**Comment by jdsika** [comment]
Please make sure to use the trust anchor accounts for the deployment of smart contracts.

**Comment by jdsika** [comment]
The suggestion is to shut down "DEMIM Main" - I am in contact with @jtdemer and will clarify this today

**Comment by jdsika** [comment]
@royscheeren we have a decision:
1) Please deactivate the deployment for the "main" branch for now.
2) Delete the resources in AWS for main. 
3) Create redirect for https://identity.ascs.digital to https://staging.identity.ascs.digital

Tell me if I missed something here
