### ISSUE TITLE
tzip21_asset_manifest.json: rights and rightsURI

### ISSUE THREAD

**Issue by jdsika** [ASCS-eV/envited-x-data-space#362]
# Let us serve the following cases:

## Open Source: Standards SPDX identifier
```
    "manifest:accessRole": "publicUser",
    "manifest:type": "license",
    "manifest:format": "html",
    "manifest:spdxIdentifier": "MIT"
    "manifest:path": {
       "https://github.com/value": "https://opensource.org/license/mit"
       "@type": "xsd:anyURI"
    }
```
-> Simply copy the spdx license indentifier and the url to the tzip21 metadata

##  providerSpecific .LICENSE custom file: "license": "LicenseRef-Custom-Commercial-Agreement"

```
    "manifest:accessRole": "registeredUser",
    "manifest:type": "license",
    "manifest:format": "md",
    "manifest:spdxIdentifier": "LicenseRef-Custom-Commercial-Agreement"
    "manifest:path": {
       "@value": "./LICENSE"
       "@type": "xsd:anyURI"
    }
```
-> upload the .LICENSE file to the right bucket/ipfs accoring to accessRole
-> add url from upload to the tzip21 metadata

## providerSpecific policy smart contract: "license": "LicenseRef-Policy-Smart-Contract"

```
    "manifest:accessRole": "publicUser",
    "manifest:type": "license",
    "manifest:format": "did",
    "manifest:spdxIdentifier": "LicenseRef-Policy-Smart-Contract"
    "manifest:path": {
       "@value": "did:tezos:NetXdQprcVkpaWU:KT1PaDvx6vApsvZchR7m3LCRQLJ1cR6C778y"
       "@type": "xsd:anyURI"
    }
```

-> Simply copy the spdx license indentifier and the url to the tzip21 metadata

**Comment by jeroenbranje** [comment]
@jdsika can you confirm what is the correct structure of manifest:license. 

I see a difference in the data with the data in the example asset.
![Image](https://github.com/user-attachments/assets/1f536fd1-b1b5-46fa-8836-a9666005184e)

**Comment by jdsika** [comment]
The data in [line 138](https://github.com/ASCS-eV/smart-contracts/blob/main/contracts/marketplace/metadata/tzip21_asset_manifest.json) ongoing in the smart-contract repository is the same as the [original asset example HD map](https://github.com/GAIA-X4PLC-AAD/hd-map-asset-example/blob/main/asset/manifest.json). This is the correct data. I was just posting a pseudo-structure to point out the different use cases.
