### ISSUE TITLE
Refactor create CID function to use correct file types

### ISSUE THREAD

**Issue by royscheeren** [ASCS-eV/envited-x-data-space#381]
# Problem statement

Currently the create filename function cannot handle the RAW codec because an incorrect filetype is being served.

We have to check the file types coming out of the visualisations and make sure we always convert to a buffer before calling createFilename so we can use createFilename and the raw codec with any filetype.

# Definition of done

The raw codec works for all files.

**Comment by jdsika** [comment]
resolved by #380
