### ISSUE TITLE
Error handling: Asset verification

### ISSUE THREAD

**Issue by jdsika** [ASCS-eV/envited-x-data-space#397]
# Asset uploader: verification steps
We have documented the verification steps in [EVES-003](https://ascs-ev.github.io/EVES/drafts/EVES-003/eves-003.html) and implemented them in the asset uploader.

# Problem
When I started creating test cases (attached) I realized that the message for the user was always the same:
![grafik](https://github.com/user-attachments/assets/0c1a43a8-6911-4008-8f21-e64a18922c65)

# Expectation
Each verfication step shall be separated into different functions of a verification module. Each module shall have test cases which confirm functionality. Each error must contain reasonable information for the user to find the issue.
The software module shall be reusable for the executing the verification needed in the indexer requested in #383 

# Some test cases
[asset_missing_data_file.zip](https://github.com/user-attachments/files/18058867/asset_missing_data_file.zip)
[asset_new_files_for_ipfs.zip](https://github.com/user-attachments/files/18058868/asset_new_files_for_ipfs.zip)
[asset_unexpected_file_in_data.zip](https://github.com/user-attachments/files/18058869/asset_unexpected_file_in_data.zip)
[asset_has_external_access_permissions.zip](https://github.com/user-attachments/files/18058870/asset_has_external_access_permissions.zip)
[asset_incorrect_license_contract_ref_did.zip](https://github.com/user-attachments/files/18058871/asset_incorrect_license_contract_ref_did.zip)
[asset_license_missing.zip](https://github.com/user-attachments/files/18058872/asset_license_missing.zip)

**Comment by jtdemer** [comment]
I also tried to upload a customer asset from Traingraphics.

I had the same poblems, no detailed and specific error information from the validator.

[asset_tg_no_playground_issues.zip](https://github.com/user-attachments/files/18129351/asset_tg_no_playground_issues.zip)
[asset_tg_issue_in_the_domainMetadata_json.zip](https://github.com/user-attachments/files/18129355/asset_tg_issue_in_the_domainMetadata_json.zip)

**Comment by jeroenbranje** [comment]
@jtdemer did you investigated what's incorrect in these assets?
I see there is no README.md in the zip and it seems also the manifest:licenseData is incorrect also missing the file.

<img width="220" alt="Scherm­afbeelding 2024-12-15 om 23 11 44" src="https://github.com/user-attachments/assets/ad29de22-b1fb-4eac-9797-66bd2a2329f5" />

This is how it is used in the example asset that is working
<img width="350" alt="Scherm­afbeelding 2024-12-15 om 23 11 56" src="https://github.com/user-attachments/assets/6176fba4-fefd-4cfa-8051-2d588efdceaa" />

@jdsika we showing a message when there is something wrong in the manifest.json with "manifest.json validation failed" or domainMetadata.json with "domainMetadata.json validation failed". There is not a detailed message with attribute or value is incorrect. Is that okay?

**Comment by jtdemer** [comment]
I'll check it again after the pull request is approved and try to debug it with the validator output.
