### ISSUE TITLE
Determine order flow

### ISSUE THREAD

**Issue by royscheeren** [ASCS-eV/envited-x-data-space#70]
# Problem statement
Dev team would like to know how a user can purchase an asset

# Definition of done
- Purchase flow is documented
- Dev team can start with breaking up tasks and start development

**Comment by jdsika** [comment]
The order flow is documented in [EVES-005](https://ascs-ev.github.io/EVES/drafts/EVES-005/eves-005.html)

**Comment by royscheeren** [comment]
Inititial spec has been documented. It is ongoing work.

This ticket will be closed.
